# Generated by Django 4.2.3 on 2023-07-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_contact_email_alter_contact_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phoneNo',
            new_name='phone',
        ),
    ]
