# Generated by Django 4.2.3 on 2023-09-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_phoneno_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='role',
            name='banner',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
