# Generated by Django 4.2.3 on 2023-09-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='id',
            new_name='googleMapId',
        ),
    ]
