# Generated by Django 4.2.3 on 2023-09-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_id_place_googlemapid'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='district',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='totalRating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='types',
            field=models.CharField(default='', max_length=500),
        ),
    ]
