# Generated by Django 4.2.3 on 2023-09-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_userfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeature',
            name='lastLatitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeature',
            name='lastLongitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
