# Generated by Django 4.2.3 on 2023-09-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_userfeature_lastlatitude_userfeature_lastlongitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDetails',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('current_opening_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('formatted_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('international_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_opening_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('curbside_pickup', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('dine_in', models.BooleanField(default=False)),
                ('editorial_summary', models.TextField(blank=True, null=True)),
                ('price_level', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reservable', models.BooleanField(default=False)),
                ('serves_beer', models.BooleanField(default=False)),
                ('serves_breakfast', models.BooleanField(default=False)),
                ('serves_dinner', models.BooleanField(default=False)),
                ('serves_lunch', models.BooleanField(default=False)),
                ('serves_vegetarian_food', models.BooleanField(default=False)),
                ('serves_wine', models.BooleanField(default=False)),
                ('takeout', models.BooleanField(default=False)),
                ('user_ratings_total', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
