# Generated by Django 4.2.3 on 2023-09-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_placedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(blank=True, max_length=50, null=True)),
                ('place_id', models.CharField(blank=True, max_length=50, null=True)),
                ('author_name', models.CharField(max_length=255)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('relative_time_description', models.CharField(max_length=255)),
                ('time', models.BigIntegerField()),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_photo_url', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('translated', models.BooleanField(default=False)),
            ],
        ),
    ]
