# Generated by Django 4.2.3 on 2023-09-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_review_userliked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeature',
            name='photoUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
